import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header"
import SubNavDropdown from "./components/SubNavDropdown";
import Banner from "./components/banner";
import UnderNavbar from "./components/dynamic_search/component/UnderNavbar";
// import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body >
        {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
          <div className="flex min-h-screen flex-col">
    <div className=" flex flex-col relative w-full">
    <Banner />
    <Header />
    
<br />

    </div>
   
   
            {children}
            <Footer />
            
          </div>
        {/* </ThemeProvider> */}

      </body>
    </html>
  )
}
